export const ruClerkLocalization = {
	locale: "ru",
	socialButtonsBlockButton: "Продолжить с {{provider|titleize}}",
	dividerText: "или",
	formFieldLabel__emailAddress: "Email адрес",
	formFieldLabel__phoneNumber: "Номер телефона",
	formFieldLabel__username: "Имя пользователя",
	formFieldLabel__password: "Пароль",
	formFieldLabel__currentPassword: "Текущий пароль",
	formFieldLabel__newPassword: "Новый пароль",
	formFieldLabel__confirmPassword: "Подтвердить пароль",
	formFieldLabel__firstName: "Имя",
	formFieldLabel__lastName: "Фамилия",
	formFieldInputPlaceholder__emailAddress: "Введите email адрес",
	formFieldInputPlaceholder__phoneNumber: "Введите номер телефона",
	formFieldInputPlaceholder__username: "Введите имя пользователя",
	formFieldInputPlaceholder__password: "Введите пароль",
	formFieldInputPlaceholder__firstName: "Введите имя",
	formFieldInputPlaceholder__lastName: "Введите фамилию",
	formFieldError__notMatchingPasswords: "Пароли не совпадают.",
	formFieldAction__forgotPassword: "Забыли пароль?",
	formFieldHintText__optional: "Необязательно",
	formButtonPrimary: "Продолжить",
	// Password validation messages
	formFieldSuccessText__passwordComplexity: "Пароль соответствует всем необходимым требованиям.",
	formFieldSuccessText__passwordsMatch: "Пароли совпадают.",
	formFieldErrorText__passwordTooShort: "Ваш пароль должен содержать 8 или более символов.",
	formFieldErrorText__passwordNotStrong: "Ваш пароль недостаточно надежен.",
	formFieldErrorText__passwordPwned: "Этот пароль был обнаружен в результате утечки данных и не может быть использован.",
	// Additional validation keys
	formFieldError__matchingPasswords: "Пароли совпадают.",
	formFieldHintText__passwordComplexity: "Пароль соответствует всем необходимым требованиям.",
	formFieldHintText__passwordMinLength: "Ваш пароль должен содержать 8 или более символов.",
	"formFieldHintText__passwordLength": "Ваш пароль должен содержать 8 или более символов.",
	"formFieldSuccessText__passwordLength": "Пароль соответствует всем необходимым требованиям.",
	"formFieldSuccessText__matchingPasswords": "Пароли совпадают.",
	"passwordComplexity": "Пароль соответствует всем необходимым требованиям.",
	"passwordsMatch": "Пароли совпадают.",
	signInEnterPasswordTitle: "Введите пароль",
	backButton: "Назад",
	footerActionLink__useAnotherMethod: "Использовать другой способ",
	badge__primary: "Основной",
	badge__thisDevice: "Это устройство",
	badge__userDevice: "Устройство пользователя",
	badge__default: "По умолчанию",
	badge__unverified: "Неподтвержденный",
	badge__requiresAction: "Требует действия",
	badge__you: "Вы",
	deviceType__mobile: "Мобильное",
	deviceType__desktop: "Компьютер",
	deviceType__unknown: "Неизвестно",
	location__tashkent: "Ташкент",
	browser__chrome: "Chrome",
	timeAgo__yesterday: "Вчера",
	timeAgo__today: "Сегодня",
	timeAgo__minutes: "{{count}} минут назад",
	timeAgo__hours: "{{count}} часов назад",
	timeAgo__days: "{{count}} дней назад",
	operatingSystem__windows: "Windows",
	operatingSystem__macOS: "macOS",
	operatingSystem__linux: "Linux",
	operatingSystem__android: "Android",
	operatingSystem__iOS: "iOS",
	formFieldLabel__signOutOfOtherSessions: "Выйти из всех других устройств",
	relativeDateToday: "Сегодня",
	relativeDateYesterday: "Вчера",
	timeFormat__12h: "{{time}} {{period}}",
	timeFormat__24h: "{{time}}",
	dateFormat__withTime: "{{date}} в {{time}}",
	timePeriod__am: "AM",
	timePeriod__pm: "PM",
	weekday__sunday: "воскресенье",
	weekday__monday: "понедельник",
	weekday__tuesday: "вторник",
	weekday__wednesday: "среда",
	weekday__thursday: "четверг",
	weekday__friday: "пятница",
	weekday__saturday: "суббота",
	signUp: {
		start: {
			title: "Создать аккаунт",
			subtitle: "чтобы продолжить в {{applicationName}}",
			actionText: "Уже есть аккаунт?",
			actionLink: "Войти",
		},
		emailCode: {
			title: "Подтвердите email",
			subtitle: "чтобы продолжить в {{applicationName}}",
			formTitle: "Код подтверждения",
			formSubtitle: "Введите код подтверждения, отправленный на ваш email",
			resendButton: "Не получили код? Отправить заново",
		},
		continue: {
			title: "Заполните пропущенные поля",
			subtitle: "чтобы продолжить в {{applicationName}}",
			actionText: "Уже есть аккаунт?",
			actionLink: "Войти",
		},
	},
	signIn: {
		start: {
			title: "Войти",
			subtitle: "чтобы продолжить в {{applicationName}}",
			actionText: "Нет аккаунта?",
			actionLink: "Зарегистрироваться",
		},
		password: {
			title: "Введите пароль",
			subtitle: "чтобы продолжить в {{applicationName}}",
			actionLink: "Использовать другой способ",
		},
		forgotPasswordAlternativeMethods: {
			title: "Забыли пароль?",
			label__alternativeMethods: "Или войдите другим способом",
			blockButton__resetPassword: "Сбросить пароль",
		},
		forgotPassword: {
			title_email: "Проверьте email",
			subtitle: "чтобы сбросить пароль",
			formTitle: "Код сброса пароля",
			formSubtitle_email: "Введите код, отправленный на ваш email",
			resendButton: "Не получили код? Отправить заново",
		},
		resetPassword: {
			title: "Сбросить пароль",
			formButtonPrimary: "Сбросить пароль",
			successMessage: "Ваш пароль был успешно изменен. Выполняется вход, пожалуйста подождите.",
		},
		emailCode: {
			title: "Проверьте email",
			subtitle: "чтобы продолжить в {{applicationName}}",
			formTitle: "Код подтверждения",
			formSubtitle: "Введите код подтверждения, отправленный на ваш email",
			resendButton: "Не получили код? Отправить заново",
		},
	},
	userProfile: {
		navbar: {
			title: "Профиль",
			description: "Информация о вашем аккаунте",
			account: "Профиль",
			security: "Безопасность",
		},
		mobileButton__menu: "Меню",
		formButtonPrimary__continue: "Продолжить",
		formButtonPrimary__finish: "Завершить",
		formButtonPrimary__save: "Сохранить",
		formButtonReset: "Отменить",
		start: {
			headerTitle__account: "Аккаунт",
			headerTitle__security: "Безопасность",
			headerSubtitle__account: "Информация аккаунта",
			headerSubtitle__security: "Управление настройками безопасности",
			profileSection: {
				title: "Профиль",
				primaryButton: "Обновить профиль",
			},
			usernameSection: {
				title: "Имя пользователя",
				primaryButton__changeUsername: "Изменить имя пользователя",
				primaryButton__setUsername: "Установить имя пользователя",
			},
			emailAddressesSection: {
				title: "Email адреса",
				primaryButton: "Добавить email адрес",
				detailsTitle__primary: "Основной email адрес",
				detailsSubtitle__primary: "Этот email адрес является основным",
				detailsAction__primary: "Завершить подтверждение",
				detailsTitle__nonPrimary: "Установить как основной email адрес",
				detailsSubtitle__nonPrimary:
					"Установите этот email адрес как основной для получения уведомлений, связанных с вашим аккаунтом.",
				detailsAction__nonPrimary: "Установить как основной",
				detailsTitle__unverified: "Неподтвержденный email адрес",
				detailsSubtitle__unverified:
					"Этот email адрес не был подтвержден и может быть ограничен в функциональности",
				detailsAction__unverified: "Завершить подтверждение",
				destructiveActionTitle: "Удалить",
				destructiveActionSubtitle: "Удалить этот email адрес и убрать его из вашего аккаунта",
				destructiveAction: "Удалить email адрес",
			},
			phoneNumbersSection: {
				title: "Номера телефонов",
				primaryButton: "Добавить номер телефона",
				detailsTitle__primary: "Основной номер телефона",
				detailsSubtitle__primary: "Этот номер телефона является основным",
				detailsAction__primary: "Завершить подтверждение",
				detailsTitle__nonPrimary: "Установить как основной номер телефона",
				detailsSubtitle__nonPrimary:
					"Установите этот номер телефона как основной для получения уведомлений, связанных с вашим аккаунтом.",
				detailsAction__nonPrimary: "Установить как основной",
				detailsTitle__unverified: "Неподтвержденный номер телефона",
				detailsSubtitle__unverified:
					"Этот номер телефона не был подтвержден и может быть ограничен в функциональности",
				detailsAction__unverified: "Завершить подтверждение",
				destructiveActionTitle: "Удалить",
				destructiveActionSubtitle: "Удалить этот номер телефона и убрать его из вашего аккаунта",
				destructiveAction: "Удалить номер телефона",
			},
			connectedAccountsSection: {
				title: "Подключенные аккаунты",
				primaryButton: "Подключить аккаунт",
				title__conectionFailed: "Повторить неуспешное подключение",
				title__connectionFailed: "Повторить неуспешное подключение",
				actionLabel__connectionFailed: "Попробовать еще раз",
				destructiveActionTitle: "Удалить",
				destructiveActionSubtitle: "Удалить этот подключенный аккаунт из вашего аккаунта",
				destructiveActionAccordionSubtitle: "Удалить подключенный аккаунт",
			},
			enterpriseAccountsSection: {
				title: "Корпоративные аккаунты",
			},
			passwordSection: {
				title: "Пароль",
				primaryButton__changePassword: "Изменить пароль",
				primaryButton__setPassword: "Установить пароль",
				primaryButton__updatePassword: "Обновить пароль",
			},
			mfaSection: {
				title: "Двухфакторная аутентификация",
				primaryButton: "Добавить двухфакторную аутентификацию",
				phoneCode: {
					destructiveActionTitle: "Удалить",
					destructiveActionSubtitle: "Удалить этот номер телефона из методов двухфакторной аутентификации",
					destructiveActionLabel: "Удалить номер телефона",
					title__default: "Фактор по умолчанию",
					title__setDefault: "Установить как фактор по умолчанию",
					subtitle__default:
						"Этот фактор будет использоваться как метод двухфакторной аутентификации по умолчанию при входе.",
					subtitle__setDefault:
						"Установите этот фактор как фактор по умолчанию, чтобы использовать его как метод двухфакторной аутентификации по умолчанию при входе.",
					actionLabel__setDefault: "Установить как по умолчанию",
				},
				backupCodes: {
					headerTitle: "Резервные коды",
					title__regenerate: "Сгенерировать резервные коды",
					subtitle__regenerate:
						"Получите новый набор безопасных резервных кодов. Предыдущие резервные коды будут удалены и не смогут быть использованы.",
					actionLabel__regenerate: "Сгенерировать коды",
				},
				totp: {
					headerTitle: "Приложение-аутентификатор",
					title: "Фактор по умолчанию",
					subtitle:
						"Этот фактор будет использоваться как метод двухфакторной аутентификации по умолчанию при входе.",
					destructiveActionTitle: "Удалить",
					destructiveActionSubtitle: "Удалить приложение-аутентификатор из методов двухфакторной аутентификации",
					destructiveActionLabel: "Удалить приложение-аутентификатор",
				},
			},
			activeDevicesSection: {
				title: "Активные устройства",
				primaryButton: "Активные устройства",
				detailsTitle: "Текущее устройство",
				detailsSubtitle: "Это устройство, которое вы используете в данный момент",
				destructiveActionTitle: "Выйти",
				destructiveActionSubtitle: "Выйти из вашего аккаунта на этом устройстве",
				destructiveAction: "Выйти из устройства",
			},
			web3WalletsSection: {
				title: "Web3 кошельки",
				primaryButton: "Web3 кошельки",
				destructiveActionTitle: "Удалить",
				destructiveActionSubtitle: "Удалить этот web3 кошелек из вашего аккаунта",
				destructiveAction: "Удалить кошелек",
			},
			deleteSection: {
				title: "Удаление аккаунта",
				primaryButton: "Удалить аккаунт",
				title__deletePage: "Удалить аккаунт",
			},
			dangerSection: {
				title: "Удалить аккаунт",
				deleteAccountButton: "Удалить аккаунт",
			},
		},
		profilePage: {
			title: "Обновить профиль",
			imageFormTitle: "Изображение профиля",
			imageFormSubtitle: "Загрузить",
			imageFormDestructiveActionSubtitle: "Удалить изображение",
			fileDropAreaTitle: "Перетащите файл сюда или...",
			fileDropAreaAction: "Выберите файл",
			fileDropAreaHint: "Рекомендуемый размер 1:1, до 10МБ.",
			readonly:
				"Информация вашего профиля предоставлена корпоративным подключением и не может быть отредактирована.",
			successMessage: "Ваш профиль был обновлен.",
		},
		usernamePage: {
			title: "Обновить имя пользователя",
			successMessage: "Ваше имя пользователя было обновлено.",
		},
		emailAddressPage: {
			title: "Добавить email адрес",
			emailCode: {
				formHint: "На этот email адрес будет отправлено письмо с кодом подтверждения.",
				formTitle: "Код подтверждения",
				formSubtitle: "Введите код подтверждения, отправленный на {{identifier}}",
				resendButton: "Не получили код? Отправить заново",
				successMessage: "Email {{identifier}} был добавлен в ваш аккаунт.",
			},
			emailLink: {
				formHint: "На этот email адрес будет отправлено письмо со ссылкой для подтверждения.",
				formTitle: "Ссылка для подтверждения",
				formSubtitle: "Нажмите на ссылку для подтверждения в письме, отправленном на {{identifier}}",
				resendButton: "Не получили ссылку? Отправить заново",
				successMessage: "Email {{identifier}} был добавлен в ваш аккаунт.",
			},
			removeResource: {
				title: "Удалить email адрес",
				messageLine1: "{{identifier}} будет удален из этого аккаунта.",
				messageLine2: "Вы больше не сможете войти, используя этот email адрес.",
				successMessage: "{{identifier}} был удален из вашего аккаунта.",
			},
			verifyTitle: "Подтвердить email адрес",
			verifySubtitle: "Чтобы закончить добавление {{identifier}}, введите код подтверждения",
			makePrimaryActionLabel: "Сделать основным",
			makePrimarySuccessMessage: "{{identifier}} теперь ваш основной email адрес.",
		},
		phoneNumberPage: {
			title: "Добавить номер телефона",
			successMessage: "{{identifier}} был добавлен в ваш аккаунт.",
			verifySubtitle: "Введите код подтверждения, отправленный на {{identifier}}",
			verifyTitle: "Подтвердить номер телефона",
			removeResource: {
				title: "Удалить номер телефона",
				messageLine1: "{{identifier}} будет удален из этого аккаунта.",
				messageLine2: "Вы больше не сможете войти, используя этот номер телефона.",
				successMessage: "{{identifier}} был удален из вашего аккаунта.",
			},
			makePrimaryActionLabel: "Сделать основным",
			makePrimarySuccessMessage: "{{identifier}} теперь ваш основной номер телефона.",
		},
		connectedAccountPage: {
			title: "Добавить подключенный аккаунт",
			formHint: "Выберите провайдера для подключения вашего аккаунта.",
			formHint__noAccounts: "Нет доступных внешних провайдеров аккаунтов.",
			socialButtonsBlockButton: "Подключить аккаунт {{provider|titleize}}",
			successMessage: "Провайдер был добавлен в ваш аккаунт",
			removeResource: {
				title: "Удалить подключенный аккаунт",
				messageLine1: "{{identifier}} будет удален из этого аккаунта.",
				messageLine2:
					"Вы больше не сможете использовать этот подключенный аккаунт, и любые зависимые функции больше не будут работать.",
				successMessage: "{{identifier}} был удален из вашего аккаунта.",
			},
		},
		passwordPage: {
			title: "Установить пароль",
			title__update: "Обновить пароль",
			changePasswordTitle: "Изменить пароль",
			readonly:
				"Ваш пароль в настоящее время не может быть изменен, поскольку вы можете войти только через корпоративное подключение.",
			successMessage: "Ваш пароль был установлен.",
			changePasswordSuccessMessage: "Ваш пароль был обновлен.",
			sessionsSignedOutSuccessMessage: "Все другие устройства были отключены.",
			checkboxInfoText__signOutOfOtherSessions:
				"Рекомендуется выйти из всех других устройств, которые могли использовать ваш старый пароль.",
		},
		mfaPage: {
			title: "Добавить двухфакторную аутентификацию",
			formHint: "Выберите метод для добавления.",
		},
		totpPage: {
			title: "Добавить приложение-аутентификатор",
			verifyTitle: "Код подтверждения",
			verifySubtitle: "Введите код подтверждения, созданный вашим аутентификатором",
			successMessage:
				"Двухфакторная аутентификация теперь включена. При входе в систему вам нужно будет ввести код подтверждения из этого аутентификатора в качестве дополнительного шага.",
			authenticatorApp: {
				infoText__ableToScan:
					"Настройте новый метод входа в вашем приложении-аутентификаторе и отсканируйте следующий QR-код, чтобы связать его с вашим аккаунтом.",
				infoText__unableToScan:
					"Настройте новый метод входа в вашем аутентификаторе и введите ключ, предоставленный ниже.",
				inputLabel__unableToScan1:
					"Убедитесь, что включены одноразовые пароли на основе времени или TOTP, затем завершите связывание вашего аккаунта.",
				inputLabel__unableToScan2:
					"Альтернативно, если ваш аутентификатор поддерживает HOTP URI, вы также можете скопировать полный URI.",
				buttonAbleToScan__nonPrimary: "Отсканируйте QR-код вместо этого",
				buttonUnableToScan__nonPrimary: "Не можете отсканировать QR-код?",
			},
			removeResource: {
				title: "Удалить двухфакторную аутентификацию",
				messageLine1: "Коды подтверждения из этого аутентификатора больше не будут требоваться при входе.",
				messageLine2: "Ваш аккаунт может быть не так безопасен. Вы уверены, что хотите продолжить?",
				successMessage: "Двухфакторная аутентификация через приложение-аутентификатор была удалена.",
			},
		},
		phoneCodePage: {
			title: "Добавить подтверждение по SMS",
			subtitle__availableAtLogin: "Установите подтверждение по SMS в качестве метода входа",
			subtitle__unavailableAtLogin: "Установите подтверждение по SMS в качестве резервного метода входа",
			successMessage:
				"SMS подтверждение теперь включено. При входе в систему вам нужно будет ввести код подтверждения, отправленный на этот номер телефона в качестве дополнительного шага.",
			removeResource: {
				title: "Удалить подтверждение по SMS",
				messageLine1: "{{identifier}} больше не будет получать коды подтверждения при входе.",
				messageLine2: "Ваш аккаунт может быть не так безопасен. Вы уверены, что хотите продолжить?",
				successMessage: "SMS подтверждение было удалено",
			},
		},
		backupCodePage: {
			title: "Добавить подтверждение резервным кодом",
			title__codelist: "Резервные коды",
			subtitle__codelist:
				"Храните их в безопасности и держите в секрете. Если вы потеряете свое устройство аутентификации, вы можете использовать резервные коды для входа.",
			infoText1: "Резервные коды будут включены для этого аккаунта.",
			infoText2:
				"Держите резервные коды в секрете и храните их в безопасности. Вы можете регенерировать резервные коды, если подозреваете, что они были скомпрометированы.",
			successSubtitle:
				"Теперь вы можете использовать один из них для входа в свой аккаунт, если потеряете доступ к своему устройству аутентификации.",
			successMessage:
				"Резервные коды теперь включены. Вы можете использовать один из них для входа в свой аккаунт, если потеряете доступ к своему устройству аутентификации. Каждый код может быть использован только один раз.",
			actionLabel__copy: "Скопировать все",
			actionLabel__copied: "Скопировано!",
			actionLabel__download: "Скачать .txt",
			actionLabel__print: "Распечатать",
		},
		deletePage: {
			title: "Удалить аккаунт",
			messageLine1: "Вы уверены, что хотите удалить свой аккаунт?",
			messageLine2: "Это действие является постоянным и необратимым.",
			actionDescription: 'Введите "Удалить аккаунт" ниже, чтобы продолжить.',
			confirm: "Удалить аккаунт",
		},
		activeDevicesPage: {
			title: "Активные устройства",
			subtitle: "Это устройство",
		},
	},
	userButton: {
		action__manageAccount: "Управление аккаунтом",
		action__signOut: "Выйти",
		action__signOutAll: "Выйти из всех аккаунтов",
		action__addAccount: "Добавить аккаунт",
	},
	unstable__errors: {
		form_code_incorrect: "Неверный код подтверждения.",
		form_identifier_exists: "Этот email адрес уже занят. Пожалуйста, попробуйте другой.",
		form_identifier_exists__email_address: "Этот email адрес уже занят. Пожалуйста, попробуйте другой.",
		form_identifier_not_found: "Пользователь с таким идентификатором не найден.",
		form_param_format_invalid__email_address: "Email адрес должен быть действительным email адресом.",
		form_param_nil: "Поле не может быть пустым.",
		form_password_incorrect: "Неверный пароль.",
		form_password_length_too_short: "Ваш пароль должен содержать 8 или более символов.",
		form_password_not_strong_enough: "Ваш пароль недостаточно надежен.",
		form_password_pwned:
			"Этот пароль был обнаружен в результате утечки данных и не может быть использован, пожалуйста, попробуйте другой пароль.",
		session_exists: "Сессия уже существует.",
		identification_deletion_failed: "Не удалось удалить последний способ идентификации.",
		// Additional password validation errors
		password_validation_length: "Ваш пароль должен содержать 8 или более символов.",
		password_validation_complexity: "Пароль соответствует всем необходимым требованиям.",
		password_validation_match: "Пароли совпадают.",
	},
};
